/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Home: typeof import('./src/components/templates/Home.vue')['default']
    Logo: typeof import('./src/components/atoms/Logo.vue')['default']
    Navbar: typeof import('./src/components/molecules/Navbar.vue')['default']
    Navigation: typeof import('./src/components/organisms/Navigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
